{% set name = "inflect" %}
{% set version = "7.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a7ce5e23d6798734f256c1ad9ed52186b8ec276f10b18ce3d3ecb19c21eb6cb6

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.8
    - setuptools >=56
    - setuptools-scm >=3.4.1
    - pip
  run:
    - python >=3.8
    - more-itertools
    - typeguard >=4.0.1
    - typing-extensions

test:
  requires:
    - pip
  imports:
    - inflect
  commands:
    - python -m pip check

about:
  home: https://github.com/jaraco/inflect
  summary: Correctly generate plurals, singular nouns, ordinals, indefinite articles; convert numbers to words
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmlandwehr
    - dbast
