{% set name = "inflect" %}
{% set version = "5.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b58d58c4e73ffca9b25e075c1c4fc9cadecbb5c99d7cd9f3cdedda73ece83c1c

build:
  skip: true  # [py<36]
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
    - setuptools-scm >=3.4.1
    - toml
  run:
    - importlib-metadata  # [py<38]
    - python

test:
  requires:
    - pip
  imports:
    - inflect
  commands:
    - python -m pip check

about:
  home: https://github.com/jazzband/inflect
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Correctly generate plurals, singular nouns, ordinals, indefinite articles; convert numbers to words
  dev_url: https://github.com/jazzband/inflect
  doc_url: https://github.com/jazzband/inflect

extra:
  recipe-maintainers:
    - pmlandwehr
    - dbast
