{% set name = "inflect" %}
{% set version = "7.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: faf19801c3742ed5a05a8ce388e0d8fe1a07f8d095c82201eb904f5d27ad571f

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=56
    - setuptools-scm >=3.4.1
    - pip
  run:
    - python >={{ python_min }}
    - more-itertools
    - typeguard >=4.0.1
    - typing-extensions

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - inflect
  commands:
    - python -m pip check

about:
  home: https://github.com/jaraco/inflect
  summary: Correctly generate plurals, singular nouns, ordinals, indefinite articles; convert numbers to words
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmlandwehr
    - dbast
