{% set name = "inflect" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5857af173e3cb986e7a83762ec808908e4b4164fa7f2b9484c0524f786c7bf82

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm >=3.4.1
    - toml
  run:
    - importlib-metadata
    - pydantic
    - python >=3.7

test:
  requires:
    - pip
  imports:
    - inflect
  commands:
    - python -m pip check

about:
  home: https://github.com/jazzband/inflect
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Correctly generate plurals, singular nouns, ordinals, indefinite articles; convert numbers to words
  dev_url: https://github.com/jazzband/inflect
  doc_url: https://github.com/jazzband/inflect

extra:
  recipe-maintainers:
    - pmlandwehr
    - dbast
